import {
    resume1,
    resume2,
    resume4,
    resume5,
    resume6,
    resume7,
    resume8,
    resume9,
    resume10,
} from "../assest";


export const CardData = [
    {
        tag: "Most popular",
        imageUrl: resume1,
        title: "Streamline Template ",
        updatedDate: "Jun 12, 2023",
        data: "Updated",
        time: "408",
        downloadCount: "times Download",
        price: "$10,00",
        originalPrice: "$23,00",
    },
    {
        tag: "Most popular",
        imageUrl: resume2,
        title: "Streamline Template ",
        updatedDate: "Jun 12, 2023",
        data: "Updated",
        time: "408",
        downloadCount: "times Download",
        price: "$10,00",
        originalPrice: "$23,00",
    },
    {
        tag: "Most popular",
        imageUrl: resume9,
        title: "Streamline Template ",
        updatedDate: "Jun 12, 2023",
        data: "Updated",
        time: "408",
        downloadCount: "times Download",
        price: "$10,00",
        originalPrice: "$23,00",
    },
    {
        tag: "Most popular",
        imageUrl: resume4,
        title: "Streamline Template ",
        updatedDate: "Jun 12, 2023",
        data: "Updated",
        time: "408",
        downloadCount: "times Download",
        price: "$10,00",
        originalPrice: "$23,00",
    },
    {
        tag: "Most popular",
        imageUrl: resume5,
        title: "Streamline Template ",
        updatedDate: "Jun 12, 2023",
        data: "Updated",
        time: "408",
        downloadCount: "times Download",
        price: "$10,00",
        originalPrice: "$23,00",
    },
    {
        tag: "Most popular",
        imageUrl: resume6,
        title: "Streamline Template ",
        updatedDate: "Jun 12, 2023",
        data: "Updated",
        time: "408",
        downloadCount: "times Download",
        price: "$10,00",
        originalPrice: "$23,00",
    },
    {
        tag: "Most popular",
        imageUrl: resume7,
        title: "Streamline Template ",
        updatedDate: "Jun 12, 2023",
        data: "Updated",
        time: "408",
        downloadCount: "times Download",
        price: "$10,00",
        originalPrice: "$23,00",
    },
    {
        tag: "Most popular",
        imageUrl: resume8,
        title: "Streamline Template ",
        updatedDate: "Jun 12, 2023",
        data: "Updated",
        time: "408",
        downloadCount: "times Download",
        price: "$10,00",
        originalPrice: "$23,00",
    },
    {
        tag: "Most popular",
        imageUrl: resume9,
        title: "Streamline Template ",
        updatedDate: "Jun 12, 2023",
        data: "Updated",
        time: "408",
        downloadCount: "times Download",
        price: "$10,00",
        originalPrice: "$23,00",
    },
    {
        tag: "Most popular",
        imageUrl: resume10,
        title: "Streamline Template ",
        updatedDate: "Jun 12, 2023",
        data: "Updated",
        time: "408",
        downloadCount: "times Download",
        price: "$10,00",
        originalPrice: "$23,00",
    },
    {
        tag: "Most popular",
        imageUrl: resume10,
        title: "Streamline Template ",
        updatedDate: "Jun 12, 2023",
        data: "Updated",
        time: "408",
        downloadCount: "times Download",
        price: "$10,00",
        originalPrice: "$23,00",
    },
    {
        tag: "Most popular",
        imageUrl: resume10,
        title: "Streamline Template ",
        updatedDate: "Jun 12, 2023",
        data: "Updated",
        time: "408",
        downloadCount: "times Download",
        price: "$10,00",
        originalPrice: "$23,00",
    },
];
